spring:
  application:
    name: create-employee-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
endpoint: /v1/create/employee